version: '3.8'

services:
  # Spring Boot 애플리케이션 컨테이너
  wishpool-app:
    build: .
    restart: always
    depends_on:
      - wishpool-db
    environment:
      # DB 호스트명 wishpool-db
      - DB_URL=${DB_URL_PROD}
      - DB_USERNAME=${DB_USER_PROD}
      - DB_PASSWORD=${DB_PASSWORD_PROD}
    ports:
      - "8000:8000"