version: '3.8'

services:
  # Spring Boot 애플리케이션 컨테이너
  wishpool-app:
    image: ${IMAGE_FULL_PATH}
    restart: always
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    - spring.datasource.url=${DB_URL_PROD}
    - spring.datasource.username=${DB_USER_PROD}
    - spring.datasource.password=${DB_PROD_PASSWORD}
    - spring.security.oauth2.client.registration.kakao.client-id=${OAUTH2_KAKAO}
    - spring.security.oauth2.client.registration.kakao.redirect-uri=${OAUTH2_REDIRECT_URL_PROD}
    - spring.jwt.secret-key=${JWT_SECRET}
    - spring.cloud.gcp.project-id=${GCP_PROJECT_ID}
    - spring.cloud.gcp.storage.bucket=${GCP_BUCKET}
    ports:
      - "${HOST_PORT}:8000"
    networks:
      - wishpool-net

networks:
  wishpool-net:
    external: true # 외부에서 생성된 네트워크를 사용하도록 설정