version: '3.8'

services:
  # Spring Boot 애플리케이션 컨테이너
  wishpool-app:
    image: ${IMAGE_FULL_PATH}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL_PROD}
      - DB_USERNAME=${DB_USER_PROD}
      - DB_PASSWORD=${DB_PROD_PASSWORD}
    ports:
      - "${HOST_PORT}:8000"
    networks:
      - wishpool-net

networks:
  wishpool-net:
    external: true # 외부에서 생성된 네트워크를 사용하도록 설정
