version: '3.8'

services:
  # Spring Boot 애플리케이션 컨테이너
  wishpool-app:
    image: ${IMAGE_FULL_PATH}
    restart: always
    environment:
      # --- 공통 설정 ---
      - SPRING_PROFILES_ACTIVE=prod

      # --- 데이터베이스 ---
      # Spring Boot가 인식하는 전체 yml 속성 이름으로 설정
      - spring.datasource.url=${DB_URL_PROD}
      - spring.datasource.username=${DB_USER_PROD}
      - spring.datasource.password=${DB_PROD_PASSWORD}

      # --- OAuth2 ---
      # [수정] yml의 전체 경로를 변수명으로 사용
      - spring.security.oauth2.client.registration.kakao.client-id=${OAUTH2_KAKAO}
      - spring.security.oauth2.client.registration.kakao.redirect-uri=${OAUTH2_REDIRECT_URL_PROD}

      # --- JWT ---
      # [수정] yml의 전체 경로를 변수명으로 사용
      - spring.jwt.secret-key=${JWT_SECRET}

      # --- GCP ---
      # [수정] yml의 전체 경로를 변수명으로 사용
      - spring.cloud.gcp.project-id=${GCP_PROJECT_ID}
      - spring.cloud.gcp.storage.bucket=${GCP_BUCKET}
    ports:
      - "${HOST_PORT}:8000"
    networks:
      - wishpool-net

networks:
  wishpool-net:
    external: true # 외부에서 생성된 네트워크를 사용하도록 설정